# Generated by Django 4.2.8 on 2023-12-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=300, verbose_name='Место, выполнения привычки')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время, выполнения привычки')),
                ('action', models.CharField(max_length=300, verbose_name='Действие')),
                ('sign_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность, выполнения привычки')),
                ('award', models.CharField(max_length=500, verbose_name='Вознаграждение')),
                ('time_to_execute', models.PositiveSmallIntegerField(verbose_name='Время на выполнение привычки')),
                ('public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
